apiVersion: "cubiclerebels.com/v1"
kind: CustomSecret
metadata:
  name: hello
spec:
  url: "http://localhost:8200"
  path: "secret/hello"
  tokenRef: "vault-secret" # name of the Kubernetes Secret where it contains the token to auth with VAULT
  secret: "name-of-secret" # name of the Kubernetes Secret in which the returned data will be stored
