apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vault2secrets
  name: vault2secrets
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault2secrets
      name: vault2secrets
    spec:
      containers:
        - name: vault2secrets
          image: cubiclerebels/vault2secrets:latest
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        - name: kubectl
          image: kelseyhightower/kubectl:1.3.4
          args:
            - "proxy"
